---
- name: Listen for alert notifications from Datadog
  hosts: localhost
  ## Listening on port 5000.
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
      ## Define the conditions we are looking for
    - name: CPU Load Trigger
      condition: "CPU Load is high" in event.payload.event_title
      ## Define the action we should take should the condition be met
      action:
        run_job_template:
          name: EDADemo-action-webhook-single-condition
          organization: "{{ job_templates_org_name | default('Foxhound') }}"



    