---
- name: Listen for alert notifications from Datadog
  hosts: localhost
  ## Listening on port 5000.
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
      ## Define the conditions we are looking for
    - name: CPU Load Trigger
      condition: event.payload.event_type == "query_alert_monitor" and event.payload.title contains "CPU Load is high"
      ## Define the action we should take should the condition be met
      action:
        run_workflow_template:
          name: WF_EDA_Action_Datadog_report_and_resolve_saturation_issue
          organization: "{{ job_templates_org_name | default('Foxhound') }}"
          job_args:
            limit: "{{ event.payload.reporting_host }}"
            extra_vars:
              reporting_host: "{{ event.payload.reporting_host }}"

    - name: Catch all other events
      # This rule will catch all other events that do not match the previous condition
      # and print them out for debugging purposes.
      # This is useful for understanding what other events are being sent by Datadog.
      # It is not necessary for the operation of the rulebook, but can help in development.
      condition: event.payload is defined
      action:
        print_event:
          pretty: true
