---
- name: Kill Stress CPU process on Linux
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Ensure stress package is installed
      ansible.builtin.package:
        name: python3-pip
        state: present

    - name: Install psutil for process management
      ansible.builtin.pip:
        name: psutil
        state: present

    - name: Getting process IDs of the process
      community.general.pids:
        name: stress
      register: pids_of_stress

    - name: Kill all stress processes
      ansible.builtin.command:
        cmd: "kill -9 {{ pids_of_stress.pids | join(' ') }}"
      register: stress_kill_output
      when: pids_of_stress.pids | length > 0
