---
- name: Stress CPU on Linux
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Add epel
      ansible.builtin.dnf:
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm"
        state: present
        disable_gpg_check: true
      become: true

    - name: Install stress tool
      ansible.builtin.package:
        name: stress
        state: present

    - name: Stress {{ stress_core_count }} cores of the CPU
      ansible.builtin.shell: "nohup stress --cpu {{ stress_core_count }} &"
      changed_when: false
